name: sos_mobile
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  image_cropper: ^1.5.1
  # local storage and cached
  cached_network_image: ^3.3.0
  shared_preferences: ^2.0.15
  flutter_native_splash: 2.4.1


  # environment
  flutter_dotenv: ^5.0.2



  # http client
  dio: ^5.4.0
  retrofit: ^4.1.0

  # serialized
  json_annotation: ^4.9.0

  # utilities
  share_plus: ^10.0.0
  flutter_local_notifications: ^17.0.0
  flutter_image_compress: ^2.1.0
  image_picker: 1.1.2
  path_provider: ^2.0.11
  # mobile_scanner: ^6.0.2

  ai_barcode_scanner: ^6.0.1




  # service locator
  get_it: ^7.7.0
  injectable: ^2.4.1

  # router
  auto_route: ^8.1.3
  go_router: ^10.1.0

  # class utils
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1

  # state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get: ^4.6.5

  # design and ui
  moon_design:
    git: https://github.com/ChhunVirak/moon_flutter.git
  flutter_dash: ^1.0.0
  another_flushbar: ^1.12.30
  pinput: ^4.0.0
  flutter_svg: ^2.0.9
  google_fonts: ^4.0.4
  flutter_animate: ^4.5.0
  gap: ^3.0.1
  cupertino_icons: ^1.0.2

  # logger
  logging: ^1.2.0

  analyzer: ^6.4.1
  logger: ^2.3.0
  lottie: ^3.0.0
  flutter_logs: ^2.1.12
  app_links: ^6.1.1
  flutter_screenutil: ^5.9.3
  pull_to_refresh: ^2.0.0
  async: ^2.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  slang: ^3.30.2
  slang_flutter: ^3.30.0
  slang_build_runner: ^3.30.0
  injectable_generator: ^2.6.1
  auto_route_generator: ^8.0.0
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0

flutter_native_splash:
  color: "#ffffff" # Default background color for light mode
  # light:
  #   color: "#ffffff"  # Background color for light mode
  #   image: assets/image/logo.jpg  # Optional: Different splash image for light mode
  # dark:
  #   color: "#000000"  # Background color for dark mode
  #   image: assets/image/logo.jpg  # Optional: Different splash image for dark mode
  image: assets/image/logo.jpg  # Default splash image (used if no mode is specified)
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: center

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true
    lottie: true

  # colors:
  #   inputs:
  #     - assets/color/colors.xml

flutter:
  uses-material-design: true
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/sfpro/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/sfpro/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/sfpro/SF-Pro-Display-Semibold.otf
          weight: 700

    - family: Kh_Bl_LazySmooth_Regular
      fonts:
        - asset: assets/fonts/Kh_Bl_LazySmooth_Regular.ttf
          style: normal
          weight: 500

  assets:
    - .env
    - assets/image/
    - assets/svg/
    - assets/svg/tabs/
    - assets/animations/
