// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3UDc8ghDE59DLNax8mFoSGBEwMGar-CA',
    appId: '1:964168453976:web:75ea690f65b4f6d4905f2d',
    messagingSenderId: '964168453976',
    projectId: 'com-kh-sos-f274f',
    authDomain: 'com-kh-sos-f274f.firebaseapp.com',
    storageBucket: 'com-kh-sos-f274f.appspot.com',
    measurementId: 'G-JNQ2CCG5ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmHYSAPBqkAiF8Xy_X1g17JyKEw7nV4DM',
    appId: '1:964168453976:android:a9cf7e6707bad904905f2d',
    messagingSenderId: '964168453976',
    projectId: 'com-kh-sos-f274f',
    storageBucket: 'com-kh-sos-f274f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArq5OifM13-RPybnTUXUqLorQeOU2GfiU',
    appId: '1:964168453976:ios:4ca0c6ff154561ff905f2d',
    messagingSenderId: '964168453976',
    projectId: 'com-kh-sos-f274f',
    storageBucket: 'com-kh-sos-f274f.appspot.com',
    androidClientId: '964168453976-0af6v53utj03944skdigg6qjjr66rh9j.apps.googleusercontent.com',
    iosClientId: '964168453976-8gloqbrdvpkmrooqkde0mqr3ro3frhaq.apps.googleusercontent.com',
    iosBundleId: 'com.kh.sos',
  );
}
